// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyCompany
{
    internal sealed partial class Vsix
    {
        public const string Id = "61a7ba6e-0cd8-4912-a6c0-ff3f86d79c2e";
        public const string Name = "My Company";
        public const string Description = @"The easiest way to share links relevant to all developers in your team";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
