// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyCompany
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMyCompanyPackageString = "d601c386-cb36-4b5a-97fe-b7671acc7b5f";
        public static Guid guidMyCompanyPackage = new Guid(guidMyCompanyPackageString);

        public const string guidMyCompanyPackageCmdSetString = "0a2b6c0c-f680-4d26-9ecd-e5a28d7e0b66";
        public static Guid guidMyCompanyPackageCmdSet = new Guid(guidMyCompanyPackageCmdSetString);

        public const string IconsString = "5057c68c-d67d-4bd6-ba1a-c109efc22adc";
        public static Guid Icons = new Guid(IconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int SubMenuGroup = 0x1030;
        public const int HRMenuGroup = 0x1040;
        public const int Wiki = 0x0100;
        public const int BuildServer = 0x0200;
        public const int HrPortal = 0x0300;
        public const int Logo = 0x0001;
    }
}